# StylizedDamage NeoForge 26.1 Mod Metadata
modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
    modId="${mod_id}"
    version="${neoforge_26_1_version}"
    displayName="${mod_name}"
    logoFile=""
    authors="${mod_authors}"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version_26_1},)"
    ordering="NONE"
    side="BOTH"
